#!/bin/sh
### BEGIN INIT INFO
# Provides:          usp-pa
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: USP Protocol Agent
# Description:       Agent for USP protocol and device management
### END INIT INFO

# Source function library
. /etc/init.d/functions

NAME="usp-pa"
DAEMON="/usr/bin/UspPa"
PIDFILE="/var/run/usp-pa.pid"
CONF_DIR="/etc/usp-pa"
DAEMON_ARGS="-v 4 -p -l syslog -r $CONF_DIR/axiros-websockets-obuspa.conf"

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration if present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

start() {
    echo -n "Starting $NAME: "
    if [ -f $PIDFILE ]; then
        pid=$(cat $PIDFILE)
        if [ -d /proc/$pid ]; then
            echo "Already running"
            return 1
        else
            rm -f $PIDFILE
        fi
    fi
    
    start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        echo "OK"
    else
        echo "FAIL"
    fi
    return $RETVAL
}

stop() {
    echo -n "Stopping $NAME: "
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        rm -f $PIDFILE
        echo "OK"
    else
        echo "FAIL"
    fi
    return $RETVAL
}

restart() {
    stop
    sleep 1
    start
}

status() {
    if [ -f $PIDFILE ]; then
        pid=$(cat $PIDFILE)
        if [ -d /proc/$pid ]; then
            echo "$NAME is running (pid $pid)"
            return 0
        else
            echo "$NAME is not running (stale pidfile)"
            return 1
        fi
    else
        echo "$NAME is not running"
        return 3
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    force-reload)
        restart
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status}"
        exit 1
        ;;
esac

exit $RETVAL
